title: [Welcome My Portfolio]
description: [This Site is for sharing my technical careers and my project portfolio.]
theme: jekyll-theme-cayman
timezone: Asia/Seoul
encoding: utf-8
defaults:
    - 
        scope:
            path: "_posts"
            type: "posts"
        values:
            layout: "posts"
            category: "posts"
    -
        scope:
            path: "projects"
            type: "pages"
        values:
            layout: "projects"
            author: "Kyoungjun Park"
            category: "projects"
    -
        scope:
            path: "pages"
            type: "pages"
        values:
            layout: "pages"
            category: "pages"
